### ISSUE TITLE
B0901T.mat

### ISSUE THREAD

**Issue by nqxytttt** [EdgarMoyete/EEG-Classification-with-CNN#1]
Hello, I have a question about how to get B0901T.mat

**Comment by EdgarMoyete** [comment]
Hello
te debes registrar en esta pagina
http://www.bbci.de/competition/iv/
te mandaran un link para poder descargar los datasets en formato gdf y la descripción la puedes encontrar en este archivo
http://www.bbci.de/competition/iv/desc_2b.pdf
Nota: para los .gdf debes usar
http://biosig.sourceforge.net/
